# Exercise 1: Python Basics

## Exercise 1.1: Variables and Lists
### Task: Create a list of 10 numbers and calculate their average

In [8]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

average = sum(numbers)/len(numbers)
print(f"{average}")

5.5


## Exercise 1.2: Functions
## Task: Write a function that takes a list and returns only even numbers

In [9]:
def get_even(list):
    even_list = []
    for number in list:
        if number % 2 == 0:
            even_list.append(number)
        else:
            continue
    return even_list

print(get_even(numbers))

[2, 4, 6, 8, 10]


## Exercise 1.3: Dictionary Operations
### Task: Count how many times each word appears in a sentence

In [13]:
def word_count(sentence):
    sentence_array = sentence.rsplit(" ")
    words = {}
    for word in sentence_array:
        if words.get(word) == None:
            words[word] = 1
        else:
            words[word] += 1
    return words


        
words = {}
print(word_count("Hello how are you doing Are you good"))


{'Hello': 1, 'how': 1, 'are': 1, 'you': 2, 'doing': 1, 'Are': 1, 'good': 1}


# Exercise 2: NumPy Basics

## Exercise 2.1: Create and Manipulate Arrays
### Task: Create a 5x5 array of random numbers

In [22]:
import numpy as np

b = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

a = np.random.random((2,2))
print(a)
print("-"*60)
print(b)

[[0.97911444 0.92979726]
 [0.13365491 0.92836236]]
------------------------------------------------------------
[[1 2 3]
 [4 5 6]]


## Exercise 3: Pandas Basics
### Exercise 3.1: Create and explore dataframe

In [ ]:
import pandas as pd

df = pd.DataFrame(
    {
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'age': [25, 30, 35, 28, 32],
    'city': ['NYC', 'LA', 'Chicago', 'NYC', 'LA'],
    'salary': [50000, 60000, 70000, 55000, 65000]
    }
)


      name  age     city  salary
2  Charlie   35  Chicago   70000
4      Eve   32       LA   65000


## Exercise 4 First ML Model
### Exercise 4.1: Train/Test Split

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
print("X shape", X.shape)

y = pd.Series(iris.target, name='species')
print("y shape", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2
)
print("train:")
print(len(X_train))
print(len(y_train))
print("test:")
print(len(X_test))
print(len(y_test))

X shape (150, 4)
y shape (150,)
train:
120
120
test:
30
30


### Exercise 4.2: Train a Classifier

In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

model = RandomForestClassifier(n_estimators=100, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

print("\nDetailed report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

Accuracy: 0.9667

Detailed report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       1.00      0.88      0.93         8
   virginica       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30



### Exercise 5.1: Load Titanic Dataset

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('titanic3.csv')
feature_cols = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare']
X = df[feature_cols]
y = df['survived']

0    1
1    1
2    0
3    0
4    0
Name: survived, dtype: int64


### Exercise 5.1:  Preprocess Titanic Data