# Exercise 1: Python Basics

## Exercise 1.1: Variables and Lists
### Task: Create a list of 10 numbers and calculate their average

In [8]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

average = sum(numbers)/len(numbers)
print(f"{average}")

5.5


## Exercise 1.2: Functions
## Task: Write a function that takes a list and returns only even numbers

In [9]:
def get_even(list):
    even_list = []
    for number in list:
        if number % 2 == 0:
            even_list.append(number)
        else:
            continue
    return even_list

print(get_even(numbers))

[2, 4, 6, 8, 10]


## Exercise 1.3: Dictionary Operations
### Task: Count how many times each word appears in a sentence

In [13]:
def word_count(sentence):
    sentence_array = sentence.rsplit(" ")
    words = {}
    for word in sentence_array:
        if words.get(word) == None:
            words[word] = 1
        else:
            words[word] += 1
    return words


        
words = {}
print(word_count("Hello how are you doing Are you good"))


{'Hello': 1, 'how': 1, 'are': 1, 'you': 2, 'doing': 1, 'Are': 1, 'good': 1}


# Exercise 2: NumPy Basics

## Exercise 2.1: Create and Manipulate Arrays
### Task: Create a 5x5 array of random numbers

In [22]:
import numpy as np

b = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

a = np.random.random((2,2))
print(a)
print("-"*60)
print(b)

[[0.97911444 0.92979726]
 [0.13365491 0.92836236]]
------------------------------------------------------------
[[1 2 3]
 [4 5 6]]


## Exercise 3: Pandas Basics
### Exercise 3.1: Create and explore dataframe

In [ ]:
import pandas as pd

df = pd.DataFrame(
    {
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'age': [25, 30, 35, 28, 32],
    'city': ['NYC', 'LA', 'Chicago', 'NYC', 'LA'],
    'salary': [50000, 60000, 70000, 55000, 65000]
    }
)

print(df[df['age'] > 30])

      name  salary
0    Alice   50000
1      Bob   60000
2  Charlie   70000
3    Diana   55000
4      Eve   65000
